services:
  mysqldb:
    image: mysql:8
    container_name: mysql-dbl
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: artgallerydbf
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: vigneshpoluru1277/artgallery-backend:latest
    container_name: springboot
    ports:
      - "2025:2004"
    depends_on:
      - mysqldb   
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: vigneshpoluru1277/artgallery-frontend:latest
    container_name: react
    ports:
      - "2002:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
