name: CI Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2 — Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3 — Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      # Step 4 — Build & Push Backend Image
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./artgallery-backend
          file: ./artgallery-backend/backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/artgallery-backend:latest

      # Step 5 — Build & Push Frontend Image
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./react
          file: ./react/frontend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/artgallery-frontend:latest
